SEO-171719-Links-With-Redirects-Typescript
syncfusion-content/typescript-docs pull request #230
Opened 2023-05-30 06:30 UTC by berylouma

Hello,

I have worked on the links with redirects and changing image names and alt text.

Regards,
Beryl.

2023-05-30 06:31 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-171719-Links-With-Redirects-Typescript](https://jenkins.syncfusion.com/job/Content/job/typescript-docs/1577/console)**

2023-05-30 06:38 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-171719-Links-With-Redirects-Typescript](https://jenkins.syncfusion.com/job/Content/job/typescript-docs/1577/console)**

2023-05-30 06:40 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-171719-Links-With-Redirects-Typescript](https://jenkins.syncfusion.com/job/Content/job/typescript-docs/1577/)<br/>**

2023-06-05 14:03 UTC, MallikaRK approved these changes
Approved

2023-06-12 08:56 UTC, berylouma commented on TypeScript/NuGet-Packages.md
> +    ![NuGet feed URL in Typescript NuGet Packages](nuget_packages_images/typescript-nuget-packages-feed-url.png)
Corrected

2023-06-12 10:02 UTC, MallikaRK requested changes
Commented

2023-06-12 10:03 UTC, MallikaRK requested changes
Approved

2023-06-12 11:32 UTC, MallikaRK approved these changes
Approved

2023-06-15 08:55 UTC, Girija-Rajendran approved these changes

2023-06-15 09:09 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-171719-Links-With-Redirects-Typescript](https://jenkins.syncfusion.com/job/Content/job/typescript-docs/1584/)<br/>**

2023-06-15 10:50 UTC, merged