SEO-176062-Typscript--control-issue-fixes
syncfusion-content/typescript-docs pull request #253
Opened 2023-09-18 12:39 UTC by Edithabich

Hi @MallikaRK ,
Have made changes on the redirect links. Please review.
Thanks.

Regards,
Edith.

2023-09-18 12:40 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-176062-Typscript--control-issue-fixes](https://jenkins.syncfusion.com/job/Content/job/typescript-docs/1591/console)**

2023-09-18 12:41 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-176062-Typscript--control-issue-fixes](https://jenkins.syncfusion.com/job/Content/job/typescript-docs/1591/)<br/>**

2023-09-19 06:12 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-176062-Typscript--control-issue-fixes](https://jenkins.syncfusion.com/job/Content/job/typescript-docs/1594/)<br/>**

2023-09-21 12:02 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-176062-Typscript--control-issue-fixes](https://jenkins.syncfusion.com/job/Content/job/typescript-docs/1598/console)**

2023-09-21 12:03 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-176062-Typscript--control-issue-fixes](https://jenkins.syncfusion.com/job/Content/job/typescript-docs/1598/)<br/>**

2023-09-28 08:51 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-176062-Typscript--control-issue-fixes](https://jenkins.syncfusion.com/job/Content/job/typescript-docs/1605/)<br/>**

2023-10-05 08:30 UTC, Yvone-Atieno requested changes
Commented

2023-10-05 08:30 UTC, Yvone-Atieno commented on TypeScript/DatePicker/How-To.md
> +You can get the browser culture name at page load or document ready state. Based on the culture name, DatePicker can be initiated with that specific culture value by assigning to [locale](https://hel
Check this KB link

2023-10-10 16:30 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-176062-Typscript--control-issue-fixes](https://jenkins.syncfusion.com/job/Content/job/typescript-docs/1608/console)**

2023-10-17 07:15 UTC, Yvone-Atieno approved these changes
Approved

2023-11-01 12:03 UTC, Aishwarya-Ganesan approved these changes
Fine.

2023-11-01 12:03 UTC, merged