SEO-176113-Image-Alt-Text-Typescript
syncfusion-content/typescript-docs pull request #262
Opened 2023-09-25 13:27 UTC by berylouma

Hello,

I have worked on the image alt text.

Regards,
Beryl.

2023-09-25 13:28 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-176113-Image-Alt-Text-Typescript](https://jenkins.syncfusion.com/job/Content/job/typescript-docs/1601/console)**

2023-09-25 13:30 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-176113-Image-Alt-Text-Typescript](https://jenkins.syncfusion.com/job/Content/job/typescript-docs/1601/console)**

2023-09-25 13:31 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-176113-Image-Alt-Text-Typescript](https://jenkins.syncfusion.com/job/Content/job/typescript-docs/1601/)<br/>**

2023-09-27 05:24 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-176113-Image-Alt-Text-Typescript](https://jenkins.syncfusion.com/job/Content/job/typescript-docs/1602/)<br/>**

2023-09-28 07:07 UTC, Yvone-Atieno requested changes
Commented

2023-09-28 07:07 UTC, Yvone-Atieno commented on TypeScript/CheckBox/Easy-customization.md
> +title: Easy-customization in TypeScript Checkbox | Syncfusion
Add the word Control

2023-09-28 07:07 UTC, Yvone-Atieno commented on TypeScript/FileExplorer/Accessing-Shared-Folder.md
> +title: Accessing shared folder in Typescript FileExplorer | Syncfusion
Add the word Control

2023-09-28 08:54 UTC, berylouma commented on TypeScript/CheckBox/Easy-customization.md
> +title: Easy-customization in TypeScript Checkbox | Syncfusion
Updated

2023-09-28 08:54 UTC, berylouma commented on TypeScript/FileExplorer/Accessing-Shared-Folder.md
> +title: Accessing shared folder in Typescript FileExplorer | Syncfusion
Updated

2023-09-28 09:03 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-176113-Image-Alt-Text-Typescript](https://jenkins.syncfusion.com/job/Content/job/typescript-docs/1606/console)**

2023-09-28 09:03 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-176113-Image-Alt-Text-Typescript](https://jenkins.syncfusion.com/job/Content/job/typescript-docs/1606/)<br/>**

2023-10-03 08:37 UTC, Yvone-Atieno approved these changes
Approved

2023-11-10 13:24 UTC, Aishwarya-Ganesan approved these changes
Fine.

2023-11-10 13:25 UTC, merged